name: 新功能建议
description: 有了好的想法
title: '[Request]: '
labels: [ "需求" ]
assignees: [ "daizihan233" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意花一些时间来填写这个内容！
        ## 以下是一些注意事项，请务必阅读让我能够更容易处理

        ### ❗ | 确定没有相同问题的ISSUE已被提出。
        ### ❔ | 截图完整聊天记录，尽量完整，不断章取义
        ### ⚠ | 如果涉及个人信息，请自行打码

        ## 如果您不知道如何有效、精准地表述，我建议您先阅读《提问的智慧》
        链接: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经仔细阅读上述教程和 [\"《提问的智慧》\"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。"
          required: true
        - label: "我确定这不是因为操作失误而引起的问题。"
          required: true
        - label: "我确定这是一个有意义的Issue，且目前没有此功能。"
          required: true
  - type: input
    id: name
    validations:
      required: true
    attributes:
      label: 新功能名称
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: 新功能描述
  - type: textarea
    id: description
    attributes:
      label: 来点色图/Memes
      description: |
        如果你不提供色图/Memes而你的issue中又有其他不符合标准的地方，那么你的issue可能会被直接删除
        色图不限类别，尽量偏二次元
        Memes 也不限类别，够沙雕就行
      value: |
        任何色图终将绳之以法，和蔼！